version: '3.8'
services:
  mcp-server:
    build: .
    container_name: mcp-server
    ports:
      - "0:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app
    environment:
      - PYTHONPATH=/app
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
