name: Deploy to Coolify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Coolify
        run: |
          curl -X POST https://coolify.yourcoolifyserver.com/api/v1/deploy -H "Authorization: Bearer ${{ secrets.COOLIFY_API_KEY }}"
