name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Check Project Structure
        run: |
          echo "Project structure:"
          ls -la
          
          if [ ! -f "package.json" ]; then
            echo "Warning: package.json not found"
          fi
          
          if [ ! -f ".gitignore" ]; then
            echo "Warning: .gitignore not found"
          fi
